# # Generated by Django 6.0.2 on 2026-05-10 08:26

# import django.db.models.deletion
# import django.utils.timezone
# import uuid
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='ChatKeyModel',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('key', models.UUIDField(default=uuid.uuid4)),
#                 ('usernames', models.JSONField(default=list)),
#             ],
#         ),
#         migrations.CreateModel(
#             name='ReceiverModel',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#         migrations.CreateModel(
#             name='SenderModel',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#         migrations.CreateModel(
#             name='ChatModel',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('text', models.TextField()),
#                 ('log', models.DateTimeField(default=django.utils.timezone.now)),
#                 ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directchat.receivermodel')),
#                 ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directchat.sendermodel')),
#             ],
#         ),
#     ]
