# Generated by Django 6.0.7 on 2026-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
