# Generated by Django 6.0.7 on 2026-09-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directchat', '0002_chatmodel_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuser',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('invisible', 'Invisible'), ('dnd', 'Do not disturb')], default='online', max_length=16),
        ),
    ]
