# Generated by Django 6.0.7 on 2026-09-26 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SEP = "\x1f"


def make_pair_key(usernames):
    return SEP.join(sorted(usernames or []))


def backfill_pair_keys(apps, schema_editor):
    """Populate pair_key for every existing ChatKeyModel row and drop duplicates.

    pair_key is UNIQUE, so historical rows that share the same usernames set
    would violate the constraint. Keep the lowest-pk row for each pair and
    delete the rest (ChatKeyModel is only a room-key registry; no FK points to
    it, so removing dupes is safe).
    """
    ChatKeyModel = apps.get_model("directchat", "ChatKeyModel")
    seen = set()
    for pk, usernames in ChatKeyModel.objects.order_by("pk").values_list("pk", "usernames"):
        pair_key = make_pair_key(usernames)
        if pair_key in seen:
            ChatKeyModel.objects.filter(pk=pk).delete()
            continue
        seen.add(pair_key)
        ChatKeyModel.objects.filter(pk=pk).update(pair_key=pair_key)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("directchat", "0003_onlineuser_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1) Add as nullable/non-unique so the backfill below can run on a
        #    populated table without a default or a NOT NULL/UNIQUE conflict.
        migrations.AddField(
            model_name="chatkeymodel",
            name="pair_key",
            field=models.CharField(max_length=300, null=True, blank=True),
            preserve_default=False,
        ),
        # 2) Backfill pair_key from usernames (same logic as
        #    ChatKeyModel.make_pair_key) and de-duplicate.
        migrations.RunPython(backfill_pair_keys, noop),
        # 3) Enforce the final schema: NOT NULL + UNIQUE (+ index).
        migrations.AlterField(
            model_name="chatkeymodel",
            name="pair_key",
            field=models.CharField(db_index=True, max_length=300, unique=True),
        ),
        migrations.CreateModel(
            name="GroupChat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("members", models.ManyToManyField(related_name="group_chats", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="GroupChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("group_chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="directchat.groupchat")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
