[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python manage.py collectstatic --noinput && python manage.py migrate --fake media 0005_mediaprofile_official_creek_dispike && python manage.py migrate --noinput && gunicorn burst.wsgi:application --workers 2 --bind 0.0.0.0:$PORT --timeout 900"