from django.urls import path
from .views import *

urlpatterns = [
    path("logingetvideo/", LoginGetVideo.as_view(), name="LoginGetVideo"),
    path("guestgetvideo/", GuestGetVideo.as_view(), name="GuestGetVideo"),
    path("watchvideo/", LoginWatchVideo.as_view(), name="WatchVideo"),
    path("guestwatchvideo/", GuestWatchVideo.as_view(), name="GuestWatchVideo"),
    path("getownvideo/", GetOwnVideo.as_view(), name="GetOwnVideo"),
    path("uploadvideo/", UploadVideo.as_view(), name="UploadVideo"),
    path("uploadcommentvideo/", UploadCommentVideo.as_view(), name="UploadCommentVideo"),
    path("pikevideo/", PikeVideo.as_view(), name="PikeVideo"),
    path("dispikevideo/", DisPikeVideo.as_view(), name="DisPikeVideo"),
    path("creekaccount/", CreekAccount.as_view(), name="CreekAccount"),
    path("studio/", Studio.as_view(), name="Studio"),
    path('studio/videos/<int:video_id>/', StudioVideoDelete.as_view(), name='studio-video-delete'),
    path("categories/", Categories.as_view(), name="Categories"),
    path("categories/manage/", CategoryManage.as_view(), name="CategoryManage"),
    path("comment/", CommentVideo.as_view(), name="CommentVideo"),
    path("pincomment/", PinComment.as_view(), name="PinComment"),
    path("mod-panel/", ModPanel.as_view()),
    path("getmod/", IfModerator.as_view(), name="GetMod"),
    path("searchvideo/", SearchVideo.as_view(), name="SearchVideo"),
    path("searchusers/", SearchUsers.as_view(), name="SearchUsers"),
    path("studio/comments/", StudioComments.as_view(), name="StudioComments"),
    path("account/", Account.as_view(), name="GetAccount"),
    path("trackretention/", TrackRetention.as_view(), name="TrackRetention"),
    path("notifications/unread-count/", NotificationUnreadCount.as_view(), name="NotificationUnreadCount"),
    path("notifications/mark-read/", NotificationMarkRead.as_view(), name="NotificationMarkRead"),
    path("notifications/mark-all-read/", NotificationMarkAllRead.as_view(), name="NotificationMarkAllRead"),
    path("notifications/", NotificationList.as_view(), name="NotificationList"),
    path("comment-like/", CommentLikeToggle.as_view(), name="CommentLikeToggle"),
    path("comment-edit/", CommentEdit.as_view(), name="CommentEdit"),
    path("comment-delete/<int:comment_id>/", CommentDelete.as_view(), name="CommentDelete"),
    path("settings/", UserSettings.as_view(), name="UserSettings"),
]
