# Generated by Django 6.0.2 on 2026-03-06 10:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_verified'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE accounts_profile ADD COLUMN IF NOT EXISTS bio text NULL;",
            reverse_sql="ALTER TABLE accounts_profile DROP COLUMN IF EXISTS bio;",
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
