# Generated by Django 6.0.2 on 2026-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_bio_alter_profile_avatar'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE accounts_profile ADD COLUMN IF NOT EXISTS bio text NULL;",
            reverse_sql="ALTER TABLE accounts_profile DROP COLUMN IF EXISTS bio;",
        ),
    ]
