# Generated by Django 6.0.7 on 2026-07-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_reply',
            field=models.BooleanField(default=True),
        ),
    ]
