# Generated by Django 6.0.7 on 2026-07-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_bio_max_length'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securitycode',
            new_name='accounts_se_user_id_f7c6ba_idx',
            old_name='accounts_sec_user_purpo_idx',
        ),
    ]
