# Generated by Django 6.0.2 on 2026-02-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Video',
            new_name='video',
        ),
    ]
