# Generated by Django 6.0.2 on 2026-02-22 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rename_video_comment_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='new_category',
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='media.categoryvideo'),
        ),
    ]
