# Generated by Django 6.0.2 on 2026-05-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_mediaprofile_official_creek_dispike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
