# Generated by Django 6.0.7 on 2026-07-19 04:44

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_video_thumbnail_alter_video_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.CreateModel(
            name='UploadRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'uploaded_at'], name='media_uploa_user_id_81af05_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_watched', models.PositiveIntegerField(default=0, help_text='Seconds watched')),
                ('session_id', models.CharField(blank=True, default='', help_text='Rough session grouping: events from same user within 30min share a session_id', max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to='media.video')),
            ],
            options={
                'indexes': [models.Index(fields=['video', 'timestamp'], name='media_watch_video_i_c4e2f7_idx'), models.Index(fields=['user', 'video'], name='media_watch_user_id_421bad_idx'), models.Index(fields=['session_id'], name='media_watch_session_39c1ea_idx')],
            },
        ),
    ]
