# Generated by Django 6.0.7 on 2026-07-20 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_comment_is_pinned_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('comment', 'New comment on your video'), ('reply', 'Reply to your comment'), ('like', 'Someone liked your video'), ('subscribe', 'New subscriber'), ('mention', 'You were mentioned')], max_length=20)),
                ('target_type', models.CharField(blank=True, default='', max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['recipient', '-timestamp'], name='media_notif_recipie_7dab3b_idx'), models.Index(fields=['recipient', 'is_read'], name='media_notif_recipie_6104f4_idx')],
            },
        ),
    ]
