# Generated by Django 6.0.7 on 2026-07-29 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_watchevent_snip_fk_wipe_views'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='watchevent',
            new_name='media_watch_snip_id_584f74_idx',
            old_name='media_watche_snip_ti_idx',
        ),
        migrations.RenameIndex(
            model_name='watchevent',
            new_name='media_watch_user_id_f57bdf_idx',
            old_name='media_watche_user_snip_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
