# Generated by Django 6.0.7 on 2026-08-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_rename_media_watche_snip_ti_idx_media_watch_snip_id_584f74_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaprofile',
            name='banner',
            field=models.TextField(blank=True, default=''),
        ),
    ]
