# Generated by Django 6.0.7 on 2026-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_mediaprofile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
