# Generated by Django 6.0.7 on 2026-08-08 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_alter_mediaprofile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snips', to='media.categoryvideo'),
        ),
    ]
