# Generated by Django 6.0.7 on 2026-08-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_modactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('CREEKTUBE', 'CreekTube'), ('YOUTUBE', 'YouTube')], default='CREEKTUBE', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_channel_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_channel_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.TextField(blank=True, default=''),
        ),
    ]
