# Generated by Django 6.0.7 on 2026-08-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_modactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#e11d48', max_length=9)),
                ('symbol', models.CharField(blank=True, default='', max_length=8)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mediaprofile',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='snip',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='snips', to='media.tag'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='media.tag'),
        ),
        migrations.AddField(
            model_name='mediaprofile',
            name='titles',
            field=models.ManyToManyField(blank=True, related_name='holders', to='media.usertitle'),
        ),
    ]
