# Generated by Django 6.0.7 on 2026-08-11 10:00

from django.db import migrations

DEFAULT_TITLES = [
    {
        "name": "Moderator",
        "color": "#e11d48",
        "symbol": "",
        "permissions": ["mod.approve", "mod.deactivate", "mod.view_logs"],
    },
    {
        "name": "Official",
        "color": "#3b82f6",
        "symbol": "",
        "permissions": ["official.badge"],
    },
]


def seed_titles(apps, schema_editor):
    UserTitle = apps.get_model("media", "UserTitle")
    for defaults in DEFAULT_TITLES:
        UserTitle.objects.get_or_create(name=defaults["name"], defaults=defaults)


def unseed_titles(apps, schema_editor):
    UserTitle = apps.get_model("media", "UserTitle")
    UserTitle.objects.filter(name__in=[t["name"] for t in DEFAULT_TITLES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_tag_usertitle_mediaprofile_tags_snip_tags_video_tags_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_titles, unseed_titles),
    ]
