# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_video_source_type_video_youtube_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Length in seconds (0 when unknown)'),
        ),
        migrations.AddField(
            model_name='video',
            name='content_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('SNIP', 'Snip')], default='VIDEO', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Length in seconds (0 when unknown)'),
        ),
    ]
