# Generated by Django 6.0.7 on 2026-08-10 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_alter_video_timestamp'),
        ('media', '0021_tag_usertitle_mediaprofile_tags_snip_tags_video_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannelFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=64)),
                ('channel_name', models.CharField(default='', max_length=255)),
                ('channel_thumbnail', models.TextField(blank=True, default='')),
                ('channel_handle', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_channel_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'channel_id')},
            },
        ),
    ]
