# Generated by Django 6.0.7 on 2026-08-10 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_alter_video_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#e11d48', max_length=9)),
                ('symbol', models.CharField(blank=True, default='', max_length=8)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mediaprofile',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='snip',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='snips', to='media.tag'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='media.tag'),
        ),
        migrations.AddField(
            model_name='mediaprofile',
            name='titles',
            field=models.ManyToManyField(blank=True, related_name='holders', to='media.usertitle'),
        ),
        migrations.CreateModel(
            name='YouTubeChannelFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=64)),
                ('channel_name', models.CharField(default='', max_length=255)),
                ('channel_thumbnail', models.TextField(blank=True, default='')),
                ('channel_handle', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_channel_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'channel_id')},
            },
        ),
    ]
