# Generated by Django 6.0.7 on 2026-08-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0022_seed_default_titles'),
        ('media', '0025_seed_default_titles'),
    ]

    operations = [
    ]
