# Generated by Django 6.0.7 on 2026-08-15 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0026_merge_20260815_2146'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnipDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnipFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('not_interested', 'Not interested (this snip)'), ('not_interested_creator', 'Not interested in this creator'), ('not_interested_topic', 'Not interested in this topic'), ('share', 'Shared'), ('report', 'Reported')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnipSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='snip',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0, help_text='Denormalized dislike counter for cheap sorting'),
        ),
        migrations.AddIndex(
            model_name='snip',
            index=models.Index(fields=['is_approved', 'visibility'], name='media_snip_is_appr_22f864_idx'),
        ),
        migrations.AddIndex(
            model_name='snip',
            index=models.Index(fields=['-timestamp'], name='media_snip_timesta_ce7f39_idx'),
        ),
        migrations.AddIndex(
            model_name='snip',
            index=models.Index(fields=['-view_count'], name='media_snip_view_co_20e79f_idx'),
        ),
        migrations.AddIndex(
            model_name='snip',
            index=models.Index(fields=['author', '-timestamp'], name='media_snip_author__776eb1_idx'),
        ),
        migrations.AddField(
            model_name='snipdislike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snipdislike',
            name='snip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='media.snip'),
        ),
        migrations.AddField(
            model_name='snipfeedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snipfeedback',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snipfeedback',
            name='snip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='media.snip'),
        ),
        migrations.AddField(
            model_name='snipfeedback',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tags', to='media.tag'),
        ),
        migrations.AddField(
            model_name='snipsave',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snipsave',
            name='snip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='media.snip'),
        ),
        migrations.AlterUniqueTogether(
            name='snipdislike',
            unique_together={('author', 'snip')},
        ),
        migrations.AddIndex(
            model_name='snipfeedback',
            index=models.Index(fields=['author', 'kind'], name='media_snipf_author__00dd56_idx'),
        ),
        migrations.AddIndex(
            model_name='snipfeedback',
            index=models.Index(fields=['author', 'snip'], name='media_snipf_author__256420_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='snipsave',
            unique_together={('author', 'snip')},
        ),
    ]
