# Generated by Django 6.0.7 on 2026-08-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0027_snipdislike_snipfeedback_snipsave_snip_dislike_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snipfeedback',
            name='reason',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
