# Generated by Django 6.0.7 on 2026-09-27 00:00

from django.db import migrations, models


def rename_source_type_values(apps, schema_editor):
    Video = apps.get_model("media", "Video")
    Video.objects.filter(source_type="CREEKTUBE").update(source_type="KREEKTUBE")


def reverse_source_type_values(apps, schema_editor):
    Video = apps.get_model("media", "Video")
    Video.objects.filter(source_type="KREEKTUBE").update(source_type="CREEKTUBE")


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0028_snipfeedback_reason"),
    ]

    operations = [
        migrations.RunPython(rename_source_type_values, reverse_source_type_values),
        migrations.AlterField(
            model_name="video",
            name="source_type",
            field=models.CharField(
                choices=[("KREEKTUBE", "Kreektube"), ("YOUTUBE", "YouTube")],
                default="KREEKTUBE",
                max_length=20,
            ),
        ),
    ]