name: Django CI

on:
  push:
    branches: [ test, main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 
      - name: SETTIN UP PYTHON
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip" 
        
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

        # deploy to vercel
  deploy-to-vercel:
    needs: build
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_ENV_PRODUCTION if github.ref_name == 'main' else secrets.VERCEL_ENV_PREVIEW }}
      # Well since we're different vercel projects for production and preview,
      #  we have set the project id based on the branch. This is a bit of a hack, but it works.
      # So when the deployment happenss, it works on PRODUCTION AND PREVIEW.
      PROD_FLAG: --prod
      ENV_TARGET: production # It works les hope
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ env.ENV_TARGET }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build ${{ env.PROD_FLAG }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Prebuilt Commit to Vercel
        run: vercel deploy --prebuilt ${{ env.PROD_FLAG }} --token=${{ secrets.VERCEL_TOKEN }}